version: 2

defaults: &defaults
  working_directory: ~/fuzzy
  docker:
    - image: circleci/node:12.5-browsers

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1.0-spago-cache-{{ .Branch }}-{{ checksum "spago.dhall" }}-{{ checksum "packages.dhall" }}
            - v1.0-spago-cache-{{ .Branch }}
            - v1.0-spago-cache-master-{{ checksum "spago.dhall" }}-{{ checksum "packages.dhall" }}
            - v1.0-spago-cache-master

      - restore_cache:
          keys:
            - v1.3-npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
            - v1.3-npm-cache-{{ .Branch }}
            - v1.3-npm-cache-master-{{ checksum "package.json" }}
            - v1.3-npm-cache-master

      - run:
          name: Verify the project builds and tests run successfully
          command: make test
          environment:
            # The machines might have more cores than `purs` can actually use.
            # Set the number of threads to two (the cores we have available).
            RTS_ARGS: +RTS -N2 -RTS

      - save_cache:
          key: v1.0-spago-cache-{{ .Branch }}-{{ checksum "spago.dhall" }}-{{ checksum "packages.dhall" }}
          paths:
            - ~/fuzzy/.spago

      - save_cache:
          key: v1.2-npm-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/fuzzy/node_modules

workflows:
    version: 2
    build:
        jobs:
            - test
